swagger: "2.0"
info:
  title: Monopoly
  description: Non-game Web API of Feodal Monopoly project
  version: 1.0.0

host: localhost:3000
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security: 
  - Bearer: []
    
paths:
  /boards:
    x-swagger-router-controller: board.controller
    get:
      operationId: getBoards
      summary: Get all available-to-play boards
      description: >
       Returns an array of boards WITHOUT adding functions to cells.
       To do so, get a single board.
      responses:
        200:
          description: OK
        default:
          description: Invalid request
          schema:
            $ref: "#/definitions/Error"

  /boards/{boardId}:
    x-swagger-router-controller: board.controller
    parameters:
      - in: path
        name: boardId
        required: true
        type: string
        pattern: '^[A-Fa-f\d]{24}$'
    get:
      operationId: getBoard
      summary: Get board by ObjectId
      responses:
        200:
          description: OK
        default:
          description: Invalid request
          schema:
            $ref: "#/definitions/Error"

  /boards/{boardId}/{modifier}:
    x-swagger-router-controller: board.controller
    parameters:
      - in: path
        name: boardId
        required: true
        type: string
        pattern: '^[A-Fa-f\d]{24}$'
      - in: path
        name: modifier
        required: true
        type: string
        enum: ['add-cell-functions']
    get:
      operationId: getBoard
      summary: Get board by ObjectId with functions for cells
      description: >
       Returns a board and add functions to cells.
      responses:
        200:
          description: OK
        default:
          description: Invalid request
          schema:
            $ref: "#/definitions/Error"

definitions:
  Error:
    properties: 
      message:
        type: string
    required:
      - message
      